### ISSUE TITLE
Rails 5: undefined method `as_api_response' for ActiveRecord_Associations_CollectionProxy

### ISSUE THREAD

**Issue by shaicoleman** [fabrik42/acts_as_api#100] opened 2016-10-20 12:59 UTC
When running the following code, I'm getting an error with Rails 5.0.

```
project_with_tasks = Project.includes(:tasks).first
render_for_api :default, json: project_with_tasks.tasks
```

I've created a sample app to reproduce this bug:
https://github.com/shaicoleman/acts-as-api-bug

And the Rails 4 version to compare
https://github.com/shaicoleman/acts-as-api-bug/tree/rails4

Backtrace:

```
NoMethodError (undefined method `as_api_response' for #<Task::ActiveRecord_Associations_CollectionProxy:0x000000048b4738>):

app/controllers/projects_controller.rb:4:in `index'
  Rendering /home/shai/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /home/shai/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /home/shai/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (1.8ms)
  Rendering /home/shai/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /home/shai/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (0.9ms)
  Rendering /home/shai/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /home/shai/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.4ms)
  Rendered /home/shai/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (13.2ms)
```

**Comment by fabrik42** [comment] 2016-10-20 13:06
Hi! Thank you for the bug report. Unfortunately I think I will not be able to take a look at it before next week, but I am happy to have a look at a pull request.

I think a workaround until then would be to convert the collection to an array:

`render_for_api :default, json: project_with_tasks.tasks.to_a`

The `as_api_response` method gets mixed into AR objects as well as into the `Array` class. Maybe we now need to mix it into another Object as well. I just want to make sure we don't clutter the namespaces of foreign classes if we don't need to.

**Comment by shaicoleman** [comment] 2016-10-20 13:09
I've tried .to_a but it changes the response format.

I didn't manage to fix it myself, so if you can look it at sometime next week, that'll be great.

**Comment by fabrik42** [comment] 2016-10-20 13:28
Ok, I will let you know if I find something out.

**Comment by fabrik42** [comment] 2016-10-29 16:31
Just a little update: I can reproduce the problem in the spec suite after updating it to Rails 5. A lot of stuff is breaking, but I'm making progress.

**Comment by shaicoleman** [comment] 2016-10-30 23:51
Thanks for looking into that, I really appreciate that

**Comment by fabrik42** [comment] 2016-11-01 16:04
Hey, I just uploaded a branch you might want to test: 

* https://github.com/fabrik42/acts_as_api/pull/101
* https://github.com/fabrik42/acts_as_api/tree/rails5

I still need to make sure there are no regression bugs with older Rails versions and a little bit of polishing, but I think we can merge this soon.

**Comment by shaicoleman** [comment] 2016-11-01 20:51
I can confirm this fixes this issue for me.

**Comment by fabrik42** [comment] 2016-11-02 16:41
This is the only regression that prevents the branch from being merged: https://github.com/fabrik42/acts_as_api/pull/98

**Comment by shaicoleman** [comment] 2016-11-02 16:45
I've done a couple more tests, and I'm seeing a couple more similar issues of the above, so it's not 100% fixed, working now on creating a reproducible case.

**Comment by fabrik42** [comment] 2016-11-02 16:46
Very cool, thanks!

**Comment by shaicoleman** [comment] 2016-11-03 00:46
Replacing ActiveRecord::Delegation with ActiveRecord::Relation in lib/acts_as_api.rb fixes the issue for  me:
```
  if defined?(ActiveRecord::Delegation)
    ActiveRecord::Delegation.include(ActsAsApi::Collection)
  end
```

```
  if defined?(ActiveRecord::Relation)
    ActiveRecord::Relation.include(ActsAsApi::Collection)
  end
```

**Comment by fabrik42** [comment] 2016-11-03 09:07
Can you provide me some failing examples so I can extend the spec suite?

**Comment by shaicoleman** [comment] 2016-11-03 16:46
I've updated the sample app to show the issue: https://github.com/shaicoleman/acts-as-api-bug

I've dug down to the root cause, and it seems to be a conflict between acts_as_api and the protected_attributes_continued gem, when the protected_attributes_continued gem is loaded first.

The workaround is either to replace ActiveRecord::Delegation with ActiveRecord::Relation or change the load order, so protected_attributes_continued loads after acts_as_api.

**Comment by fabrik42** [comment] 2016-11-04 16:25
Wow, thanks for updating the example app, this helped me a lot!

I am not sure why this happens, I guess the protected attributes gem changes internals from `ActiveRecord`. However, I think it is fine to include the collection helpers in every single AR relation class, instead of the delegation class.

I updated the PR branch accordingly.

For the other regression I was seeing, I opened a ticket in the rails repo. I am not sure of this is now intended behavior or a bug in rails. https://github.com/rails/rails/issues/26959

**Comment by fabrik42** [comment] 2016-11-08 16:03
@shaicoleman I think I fixed the last bug. It was a mistake on my side :\

If you can confirm that the rails 5 branch works for you, I will merge it and release a new version of the gem.

**Comment by shaicoleman** [comment] 2016-11-08 16:13
Looks good, but I think you need to bump the version higher, either to 0.5.0 or to 1.0.0

**Comment by fabrik42** [comment] 2016-11-08 16:19
Yes, I will bump the version before the release :)

Shai Coleman schrieb:

**Comment by fabrik42** [comment] 2016-11-09 14:17
Hey, I just released a new version of the gem. After the last fixes it should be completely backwards compatible, so I am releasing it under the version 0.4.4.

https://rubygems.org/gems/acts_as_api/versions/0.4.4

Thanks again for your help!

**Closed by fabrik42** 2016-11-09 14:17 UTC
